[package]
name = "palette_inspector"
version = "0.1.0"
authors = ["Dakota Sankey <dakotasankey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
radix_fmt = "1.0.0"